services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sample_db
      - SECRET_KEY=sample-secret-key-for-development-only-change-in-production-2024
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=sample_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
